### ISSUE TITLE
build ios fail

### ISSUE THREAD

**Issue by lordmen99** [basitmir/cab_booking#1]
Hi, i try build in ios but cant success, here for log :

`Launching` lib/main.dart on iPhone XS Max in debug mode...
/Users/adminxp/Documents/LARACLASSAPPFLUTTER/cab_booking-master/ios/Runner/Info.plist: Property List error: Found non-key inside <dict> at line 31 / JSON error: JSON text did not start with array or object and option to allow fragments not set.
Running Xcode build...
Xcode build done.                                            4.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    warning: Capabilities for Runner may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'Runner')
    /Users/adminxp/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/app_settings-1.0.6/ios/Classes/AppSettingsPlugin.m:2:9: fatal error: 'app_settings/app_settings-Swift.h' file not found
    #import <app_settings/app_settings-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone XS Max.

**Comment by basitmir** [comment]
> Hi, i try build in ios but cant success, here for log :
> 
> `Launching` lib/main.dart on iPhone XS Max in debug mode...
> /Users/adminxp/Documents/LARACLASSAPPFLUTTER/cab_booking-master/ios/Runner/Info.plist: Property List error: Found non-key inside at line 31 / JSON error: JSON text did not start with array or object and option to allow fragments not set.
> Running Xcode build...
> Xcode build done. 4.4s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
> ** BUILD FAILED **
> 
> Xcode's output:
> ↳
> warning: Capabilities for Runner may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'Runner')
> /Users/adminxp/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/app_settings-1.0.6/ios/Classes/AppSettingsPlugin.m:2:9: fatal error: 'app_settings/app_settings-Swift.h' file not found
> #import <app_settings/app_settings-Swift.h>
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> note: Using new build systemnote: Planning buildnote: Constructing build description
> 
> Could not build the application for the simulator.
> Error launching application on iPhone XS Max.

We haven't tested it on iOS. You have to resolve it yourself 😬. 
Although android is working perfectly fine

**Comment by lordmen99** [comment]
ok, i will try fix it. btw this app when rider request driver, in driver app will show popup request booking?

**Comment by basitmir** [comment]
> ok, i will try fix it. btw this app when rider request driver, in driver app will show popup request booking?

@lordmen99 Sorry for the late response. NO, i haven't worked on popup notifications
